### ISSUE TITLE
Exiting Recursive File Search

### ISSUE THREAD

**Issue by kingbari** [Shougo/denite.nvim#568] opened 2019-01-30 19:58 UTC
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
When executing `:Denite -direction=dynamicbottom -auto-preview file_rec<CR>` followed by `escape` or `ctrl-o q` the preview window remains open resulting in a frame with horizontally split windows.

## Expected
Pressing `escape` or `ctrl-o q` closes preview window leaving only original window open.

## Environment Information (Required!)

 * denite version (SHA1):
Version 2.0

 * OS:
Mac OS Mojave - 10.14.2

 * Vim/neovim version:
VIM - Vi IMproved 8.1 (2018 May 18, compiled Dec 13 2018 12:08:00)
macOS version
Included patches: 1-577
Compiled by Homebrew
Huge version with MacVim GUI.

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Minimal .vimrc
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugins')
  Plug 'chriskempson/base16-vim'
  Plug 'davidhalter/jedi-vim'
  Plug 'dracula/vim'
  Plug 'eagletmt/ghcmod-vim'
  Plug 'eagletmt/neco-ghc'
  Plug 'fatih/vim-go', {'do': ':GoUpdateBinaries'}
  Plug 'fsharp/vim-fsharp'
  Plug 'let-def/ocp-indent-vim'
  Plug 'mileszs/ack.vim'
  Plug 'neomake/neomake'
  if has('nvim')
    Plug 'Shougo/deoplete.nvim', {'do': ':UpdateRemotePlugins'}
  else
    Plug 'Shougo/deoplete.nvim'
    Plug 'roxma/nvim-yarp'
    Plug 'roxma/vim-hug-neovim-rpc'
  endif
  Plug 'Shougo/denite.nvim'
  Plug 'Shougo/vimproc.vim', {'do': 'make'}
  Plug 'scrooloose/nerdtree'
  Plug 'ternjs/tern_for_vim', {'do': 'cd ~/.vim/plugins/tern_for_vim && npm install'}
  Plug 'tpope/vim-surround'
  Plug 'tpope/vim-fugitive'
  Plug 'vim-airline/vim-airline'
  Plug 'vim-airline/vim-airline-themes'
  Plug 'vim-scripts/paredit.vim'
call plug#end()

nnoremap <leader>f :Denite -direction=dynamicbottom -auto-preview file_rec<CR>
nnoremap <leader>b :Denite -direction=dynamicbottom -auto-preview buffer<CR>

call denite#custom#var('file/rec', 'command', ['ag', '--follow', '-g', '--nogroup', '--nocolor', '-u', ''])
call denite#custom#var('grep', 'command', ['ag'])
call denite#custom#var('grep', 'default_opts', ['-i', '--vimgrep'])
call denite#custom#var('grep', 'recursive_opts', [])
call denite#custom#var('grep', 'pattern_opt', [])
call denite#custom#var('grep', 'separator', ['--'])
call denite#custom#var('grep', 'final_opts', [])

```

## How to reproduce problems from neovim startup (Required!)

 1. Open Vim
 2. Change to target directory (see screenshot 1)
 3. Execute `:Denite -direction=dynamicbottom -auto-preview file_rec<CR>` (see screenshot 2)
 4. Press `escape` (see screenshot 3)

## Screenshot (if possible)
**Screenshot 1**
<img width="1235" alt="step1-empty-buffer" src="https://user-images.githubusercontent.com/2574031/52008645-eacc0400-2485-11e9-8c93-e107455b2e74.png">

**Screenshot 2**
<img width="1235" alt="step2-file_rec" src="https://user-images.githubusercontent.com/2574031/52007524-7728f780-2483-11e9-9553-a5e549829846.png">

**Screenshot 3**
<img width="1235" alt="step3-escape" src="https://user-images.githubusercontent.com/2574031/52008655-f0294e80-2485-11e9-896d-d5abbdb18a01.png">

**Comment by Shougo** [comment] 2019-02-02 07:12
I have tested the minimal vimrc and I cannot reproduce it.
Closing.

Please upload the minimal vimrc like this.

```vim
set rtp+=~/work/denite.nvim
```

**Closed by Shougo** 2019-02-02 07:12 UTC
