### ISSUE TITLE
Couldn't find python executable

### ISSUE THREAD

**Issue by rickywu** [Shougo/denite.nvim#419] opened 2018-01-22 09:57 UTC
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
Denite file_rec return Couldn't find python executable

## Environment Information (Required!)

 * denite version(SHA1):

 * OS:
Windows 10
 * Vim/neovim version:
vim 8.0

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
Plug 'Shougo/denite.nvim'
```

Others:

Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)] on win32
deoplete.nvim works well 

C:\Users\Ricky>which python
/d/Program Files/Python/python

C:\Users\Ricky>which python3
/d/Program Files/Python/python3

**Comment by rickywu** [comment] 2018-01-22 10:03
Seems it's plugin conflict problem, I'll reopen if find which one affect it.

**Comment by Shougo** [comment] 2018-01-23 02:41
I cannot reproduce the problem.
Please test this in Vim command line.

```vim
python3 import shutil
python3 print(shutil.which('python3'))
python3 print(shutil.which('python'))
```

**Comment by Shougo** [comment] 2018-01-23 02:42
```
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)] on win32
deoplete.nvim works well

C:\Users\Ricky>which python
/d/Program Files/Python/python

C:\Users\Ricky>which python3
/d/Program Files/Python/python3
```

It must be checked in Python environment.

**Comment by Shougo** [comment] 2018-01-23 02:54
And please check below result.

```vim
python3 import sys
python3 print(sys.executable)
```

**Comment by rickywu** [comment] 2018-01-23 02:54
python3 import shutil      no error 
python3 print(shutil.which('python3')) : d:\Program Files\Python\python3.EXE
python3 print(shutil.which('python')) : d:\Program Files\Python\python.EXE  (I copied python3 as python)

**Comment by Shougo** [comment] 2018-01-23 03:01
Please test this.

https://github.com/Shougo/denite.nvim/issues/419#issuecomment-359657316

**Comment by rickywu** [comment] 2018-01-23 03:16
@Shougo See my comments before, already tested the two commands

**Comment by Shougo** [comment] 2018-01-23 03:17
Please do this.

```
python3 import sys
python3 print(sys.executable)
```

I want to use `sys.executable` instead.  But the test is needed.

**Comment by rickywu** [comment] 2018-01-23 03:18
python3 import sys no error
python3 print(sys.executable) d:\Program Files\Vim\vim80\gvim.exe

Is the 2nd output gvim.exe correct?

**Comment by Shougo** [comment] 2018-01-23 03:22
OH, I cannot use it...

**Comment by Shougo** [comment] 2018-01-23 03:25
I don't understand why `shutil.which()` does not work...

**Comment by tracyone** [comment] 2018-01-23 03:29
You should set pythondll or pythonthreedll

https://github.com/tracyone/vinux/blob/master/autoload/te/feat.vim#L237-L238

**Comment by Shougo** [comment] 2018-01-23 03:33
Please test below patch.

```patch
diff --git a/rplugin/python3/denite/source/file_rec.py b/rplugin/python3/denite/source/file_rec.py
index bf90100..a8576d0 100644
--- a/rplugin/python3/denite/source/file_rec.py
+++ b/rplugin/python3/denite/source/file_rec.py
@@ -5,7 +5,6 @@
 # ============================================================================

 import argparse
-import shutil
 from .base import Base
 from denite.process import Process
 from os import path, pardir
@@ -113,13 +112,9 @@ class Source(Base):
         current_folder, _ = path.split(__file__)
         scantree_py = normpath(join(current_folder, pardir, 'scantree.py'))

-        if shutil.which('python3') is not None:
-            python_exe = 'python3'
-        else:
-            python_exe = 'python'
-        if shutil.which(python_exe) is None:
-            raise FileNotFoundError("Coudn't find {} executable!".format(
-                                    python_exe))
+        python_exe = self.vim.call('exepath', 'python3')
+        if not python_exe:
+            raise FileNotFoundError("Coudn't find python3 executable!")

         return [python_exe, scantree_py, '--ignore', ignore,
                 '--path', ':directory']
```

**Comment by rickywu** [comment] 2018-01-23 03:36
Never mind python problem..., I tried restart Windows it work now but seems encoding problem here
![denite](https://user-images.githubusercontent.com/442398/35256980-b08f4708-0031-11e8-95a8-d5fdc3b88da6.png)

**Comment by Shougo** [comment] 2018-01-23 03:38
Oh.

**Closed** 2018-01-23 03:39 UTC
Labels: Windows, cannot reproduce

**Comment by Shougo** [comment] 2018-01-23 03:41
denite.nvim converts the output encoding to `encoding` option.
You should check `encoding` option value and Python3 command encoding.

**Comment by Shougo** [comment] 2018-01-23 03:43
You can check the original encoding by `python3 scantree.py --path directory`.
scantree.py is in denite.nvim repository.

**Comment by rickywu** [comment] 2018-01-23 04:29
encoding in vim is utf-8 also I test in python sys.getdefaultencoding is also utf-8, shouldn't have encoding problem here

**Comment by Shougo** [comment] 2018-01-23 04:48
I don't know the reason.
You can research the problem.

https://github.com/Shougo/denite.nvim/blob/master/rplugin/python3/denite/process.py#L50

The encoding convertion is implemented here.
The PR is wellcome.

**Comment by Shougo** [comment] 2018-01-23 04:52
> encoding in vim is utf-8 also I test in python sys.getdefaultencoding is also utf-8, shouldn't have encoding problem here

I know.  But more research is needed.
Because

> Never mind python problem..., I tried restart Windows it work now but seems encoding problem here

The initial problem also should not have, but it is fixed by restart.
