### ISSUE TITLE
Denite dein cursor issue

### ISSUE THREAD

**Issue by petobens** [Shougo/denite.nvim#449] opened 2018-02-20 19:22 UTC
I'm calling Denite's dein source with
```vim
function! s:dein_update()
  call dein#update()
  Denite -no-quit -mode=normal dein_log:!
endfunction
nnoremap <Leader>bu :call <SID>dein_update()<CR>
```
In the gif below you can see that when I press `<CR>` on one of the candidates url the cursor moves back at the very bottom of denite buffer:

![feb-20-2018 16-17-53](https://user-images.githubusercontent.com/2583971/36444400-0ffae27c-165a-11e8-83ab-d7bbb3132989.gif)

I expect it to remain at the same position. For the record my denite settings are the following:
```
call denite#custom#option('default', {
            \ 'auto_resize': 1,
            \ 'auto_resume': 1,
            \ 'statusline': 0,
            \ 'winheight': 15,
            \ 'updatetime': 100,
            \ 'reversed': 1,
            \ 'prompt': '❯',
            \ 'prompt_highlight': 'Function',
            \ 'highlight_matched_char': 'Operator',
            \ 'highlight_matched_range': 'None',
            \ 'highlight_mode_insert': 'WildMenu'
            \ })
```

I can cook up a better minimal vimrc if you want but i think the problem is visible as it is.
Thanks in advance

**Comment by Shougo** [comment] 2018-02-21 02:23
Have you read the issue template?

I think your denite.nvim is not the latest version.
I cannot reproduce the problem.

**Comment by Shougo** [comment] 2018-02-21 02:24
I will close the issue.
Because, you have ignored the issue template and I cannot reproduce the behavior.
Sorry.

**Comment by petobens** [comment] 2018-05-09 21:03
Sorry for the late reply. Here there is a way to reproduce the issue. Consider the following minimal `init.vim`:
```vim
set nocompatible

let $DOTVIM = expand('$HOME/.vim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/denite.nvim
filetype plugin indent on


call denite#custom#option('default', {
            \ 'auto_resize': 1,
            \ 'reversed': 1,
            \ })

call denite#custom#map('normal', '<C-n>', '<denite:move_to_next_line>',
    \ 'noremap')
call denite#custom#map('normal', '<C-p>', '<denite:move_to_previous_line>',
    \ 'noremap')
```
Now (as in the GIF) run `:Denite -no-quit -mode=normal file` and select one of the candidates in the middle. After pressing enter the cursor wiill then jump to the bottom of the Denite window. I expect the cursor to stay at the selected candidate position:

![may-09-2018 17-59-11](https://user-images.githubusercontent.com/2583971/39839655-3e7fca22-53b3-11e8-8b26-ba7b858bab52.gif)

**Closed** 2018-05-13 01:38 UTC
Labels: cannot reproduce

**Comment by petobens** [comment] 2018-05-13 14:07
Thanks!

**Comment by petobens** [comment] 2018-05-13 14:14
After this change (using the same minimal vimrc) the cursor is at the top of the candidates when it should be at the bottom:

![may-13-2018 10-13-37](https://user-images.githubusercontent.com/2583971/39968140-6c0720f4-5696-11e8-9090-9e17deabddfe.gif)

**Comment by Shougo** [comment] 2018-05-13 14:30
Hm.  I should remove the feature completely.
Because it is buggy and hard to fix.

I should not implement the feature.
It is my fault.

**Comment by petobens** [comment] 2018-05-13 15:46
Ok. No problem.

**Comment by Shougo** [comment] 2018-05-14 14:43
Fixed

**Comment by petobens** [comment] 2018-05-14 17:52
Thank you!

**Comment by petobens** [comment] 2018-05-14 17:52
I really like this feature :)
