### ISSUE TITLE
gather_candidates broken

### ISSUE THREAD

**Issue by tex** [Shougo/denite.nvim#601] opened 2019-03-24 16:37 UTC
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary

This commit
b89e8971c0a573ca69fbc50495c4324d5d488e89
breaks file_mru and buffer sources (I tested only those two so far).

```
[denite] Traceback (most recent call last):                                                                                             
[denite]   File "/home/milan/.vim/plugged/denite.nvim/rplugin/python3/denite/rplugin.py", line 25, in start                             
[denite]     return ui.start(args[0], context)                                                                                          
[denite]   File "/home/milan/.vim/plugged/denite.nvim/rplugin/python3/denite/ui/default.py", line 78, in start                          
[denite]     self._start(context['sources_queue'][0], context)                                                                          
[denite]   File "/home/milan/.vim/plugged/denite.nvim/rplugin/python3/denite/ui/default.py", line 136, in _start                        
[denite]     self.init_denite()                                                                                                         
[denite]   File "/home/milan/.vim/plugged/denite.nvim/rplugin/python3/denite/ui/default.py", line 684, in init_denite                   
[denite]     self._denite.start(self._context)                                                                                          
[denite]   File "/home/milan/.vim/plugged/denite.nvim/rplugin/python3/denite/denite.py", line 35, in start                              
[denite]     self._load_sources(context)                                                                                                
[denite]   File "/home/milan/.vim/plugged/denite.nvim/rplugin/python3/denite/denite.py", line 322, in _load_sources                     
[denite]     source = Source(self._vim)                                                                                                 
[denite] TypeError: Can't instantiate abstract class Source with abstract methods gather_candidates                                     
[denite] Please execute :messages command.   
```

## Expected

No error.

## Environment Information (Required!)

 * denite version (SHA1):

 * OS:

 * Vim/neovim version:

 * `:checkhealth` or `:CheckHealth` result(neovim only):

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/denite.nvim/
```

## How to reproduce problems from neovim startup (Required!)

 1. foo
 2. bar
 3. baz

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

**Comment by Shougo** [comment] 2019-03-24 23:33
I have tested it with minimal vimrc, but I don't reproduce the error.
And I don't get same errors from other people?

Why?  I will close it.  Because you don't upload the minimal vimrc.

**Comment by Shougo** [comment] 2019-03-24 23:38
Please read this.

> Warning: I will close the issue without the minimal init.vim and the reproduction instructions.

**Comment by Shougo** [comment] 2019-03-24 23:39
> breaks file_mru and buffer sources (I tested only those two so far).

I think you have created broken source does not override `gather_candidates()` method.

**Comment by username4gh** [comment] 2019-03-25 03:20
My case is while i use the `denite-gtags` along with the https://github.com/Shougo/denite.nvim/commit/b89e8971c0a573ca69fbc50495c4324d5d488e89 version i got the same error.

While i altered the `_load_sources()` inside the `/path/to/denite.nvim/rplugin/python3/denite/denite.py`

```
def _load_sources(self, context):
        import denite.source # noqa
        rplugins = import_rplugins('Source', context, 'source', [
            normcase(normpath(x.path))
            for x in self._sources.values()
        ])
        from denite import util
        import inspect
        for Source, path, _ in rplugins:
            if inspect.isabstract(Source):
               util.error(self._vim, path)
```

it produces

```
[denite] /xxx/.vim/plugged/denite-gtags/rplugin/python3/denite/source/denite_gtags/gtags_base.py
[denite] /xxx/.vim/plugged/denite-gtags/rplugin/python3/denite/source/denite_gtags/tags_base.py
```

My guess is `find_plugins()` method inside `/path/to/denite.nvim/rplugin/python3/denite/util.py` does not ignore these two files that contain abstract subclass of the `Source` class

Although i'm not sure why these two files already implemented the `gather_candidates()` , the error message is still `Can't instantiate abstract class Source with abstract methods gather_candidates`.

**Comment by tex** [comment] 2019-03-25 05:37
Oh, sorry fot that. Yes I use denite gtags plugin.

**Comment by Shougo** [comment] 2019-03-25 05:55
OK.  I will fix it later.

**Closed** 2019-03-25 12:35 UTC

**Comment by tex** [comment] 2019-03-25 12:50
Thanks!
