### ISSUE TITLE
default action performed in wrong buffer

### ISSUE THREAD

**Issue by tex** [Shougo/denite.nvim#749] opened 2020-02-02 17:57 UTC
nvim
:e a.txt
:split b.txt
move cursor to a.txt (top buffer)
:Denite file
select file c.txt and hit enter (default action)
file c.txt is in place of b.txt

I expect the file a.txt to be replaced by c.txt (cursor was there)

**Comment by Shougo** [comment] 2020-02-02 23:38
Why do you ignore the issue template???
I can ignore your issue.

**Comment by Shougo** [comment] 2020-02-02 23:45
```vim
set runtimepath+=~/work/denite.nvim/
set runtimepath+=~/work/nvim-yarp/
set runtimepath+=~/work/vim-hug-neovim-rpc/

filetype plugin indent on

autocmd FileType denite call s:denite_my_settings()
function! s:denite_my_settings() abort
  nnoremap <silent><buffer><expr> q denite#do_map('quit')
  nnoremap <silent><buffer><expr>  <CR>     denite#do_map('do_action')
  nnoremap <silent><buffer><expr>  <Space>  denite#do_map('toggle_select').'j'
  nnoremap <silent><buffer><expr>  a        denite#do_map('choose_action')
  nnoremap <silent><buffer><expr>  d        denite#do_map('do_action', 'delete')
  nnoremap <silent><buffer><expr>  p        denite#do_map('do_action', 'preview')
  nnoremap <silent><buffer><expr>  i        denite#do_map('open_filter_buffer')
  nnoremap <silent><buffer><expr>  <Esc>    denite#do_map('quit')
endfunction
```

I don't reproduce the problem with minimal vimrc.
Closing due to ignore the issue template.

**Comment by tex** [comment] 2020-02-03 20:12
`init-minimal.vim` is your minimal config as provided in this thread.

```
milan@nixos> mkdir a                                                                                                              ~/tmp
milan@nixos> cd a                                                                                                                 ~/tmp
milan@nixos> echo a > a.txt                                                                                                     ~/tmp/a
milan@nixos> echo b > b.txt                                                                                                     ~/tmp/a
milan@nixos> echo c > c.txt                                                                                                     ~/tmp/a
milan@nixos> nvim -u  ~/.config/nvim/init-minimal.vim   
```
```
:e a.txt
:split b.txt                     (cursor in b.txt buffer)
:Denite file
(select c.txt, hit enter) (there are b.txt and c.txt buffers, but there should be c.txt and a.txt)
```

**Comment by Shougo** [comment] 2020-02-03 23:42
Reproduced.

**Closed** 2020-02-03 23:41 UTC
Labels: cannot reproduce, needs reproduction instructions

**Comment by tex** [comment] 2020-02-04 05:22
thank you!
