### ISSUE TITLE
Navigating grep buffer is very slow (denite:move_to_next_line)

### ISSUE THREAD

**Issue by dmdque** [Shougo/denite.nvim#254] opened 2017-04-19 21:40 UTC
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary
Moving through the `Denite grep` results buffer (j and k to move up and down) is extremely slow when there are many results. It was fast with Unite.

## Expected
Moving through results buffer should be fast.

## Environment Information (Required!)

 * denite version(SHA1):

 * OS:
El Capitan 10.11.6

 * Vim/neovim version:
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 19 2017 12:11:04)
MacOS X (unix) version
Included patches: 1-567
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     -tcl
-balloon_eval    +folding         +mouse_xterm     +termguicolors
-browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     -gettext         -mzscheme        +textobjects
+channel         -hangul_input    +netbeans_intg   +timers
+cindent         +iconv           +num64           +title
-clientserver    +insert_expand   +packages        -toolbar
+clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        +perl            +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       -python          +vreplace
+cscope          +lispindent      +python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con      -lua             +rightleft       +writebackup
+diff            +menu            +ruby            -X11
+digraphs        +mksession       +scrollbind      -xfontset
-dnd             +modify_fname    +signs           -xim
-ebcdic          +mouse           +smartindent     -xpm
+emacs_tags      -mouseshape      +startuptime     -xsmp
+eval            +mouse_dec       +statusline      -xterm_clipboard
+ex_extra        -mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax          
+farsi           +mouse_netterm   +tag_binary      
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -framework Cocoa   -mmacosx-version-min=10.11 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.24.1/lib/perl5/5.24.1/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc  -L/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/config-3.6m-darwin -lpython3.6m -framework CoreFoundation  -lruby.2.4.1 -lobjc    

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/denite.nvim/
```

## The reproduce ways from neovim starting (Required!)

 1. vim
 2. :Denite grep foobar -mode=normal
 3. j/k (move_to_next_line)

**Comment by Shougo** [comment] 2017-04-19 23:19
`:help denite-options-updatetime`

**Comment by Shougo** [comment] 2017-04-19 23:20
> It was fast with Unite.

I don't think so.

**Comment by dmdque** [comment] 2017-04-19 23:24
It's not related to filtering the results, so I don't think `updatetime` helps. When they're all listed, simply moving up or down the list (with j/k) is very slow with Denite. If I press down multiple times, it will keep scrolling even after I stop typing. With Unite it was instant.

**Comment by dmdque** [comment] 2017-04-19 23:26
Note that it's especially slow when there are lots of results in the buffer.
![image](https://cloud.githubusercontent.com/assets/5205766/25206465/f5be11f6-251c-11e7-8bd2-4ae7df581b1f.png)

**Comment by Shougo** [comment] 2017-04-19 23:28
Really?  I cannot reproduce that.

@lambdalisue Can you reproduce the problem?
It may be prompt problem.

**Comment by Shougo** [comment] 2017-04-19 23:37
More users tests are needed.

**Comment by Shougo** [comment] 2017-04-19 23:37
@dmdque Please upload the video.

**Comment by dmdque** [comment] 2017-04-19 23:47
Here's a video showing what I experience:
https://youtu.be/mZzuaI4y0FU

Note the virtual keyboard.

**Comment by Shougo** [comment] 2017-04-19 23:48
I will check it later.

**Comment by Shougo** [comment] 2017-04-19 23:54
I think your highlight in the source is slow.

**Comment by dmdque** [comment] 2017-04-19 23:57
I just tried with nvim and it's just as laggy.

What do you mean by highlight in the source? How do I fix it?

**Comment by dmdque** [comment] 2017-04-19 23:58
My basic `init.vim`:
    if &compatible
      set nocompatible
    endif
    set runtimepath+=~/.nvim/bundle/repos/github.com/Shougo/dein.vim

    if dein#load_state('~/.nvim/bundle/repos/github.com/Shougo/dein.vim')
      call dein#begin('~/.nvim/bundle/repos/github.com/Shougo/dein.vim')

      call dein#add('~/.nvim/bundle/repos/github.com/Shougo/dein.vim')
      call dein#add('Shougo/denite.nvim')

      call dein#end()
      call dein#save_state()
    endif

    filetype plugin indent on
    syntax enable


    " Denite Ripgrep command on grep source
    call denite#custom#source('grep', 'max_candidates', 100)  " not sure if this is working
    call denite#custom#var('grep', 'command', ['rg'])
    call denite#custom#var('grep', 'default_opts',
    \ ['--vimgrep', '--no-heading', '--smart-case'])
    call denite#custom#var('grep', 'recursive_opts', [])
    call denite#custom#var('grep', 'pattern_opt', ['--regexp'])
    call denite#custom#var('grep', 'separator', ['--'])
    call denite#custom#var('grep', 'final_opts', [])


    nnoremap <C-F> :<C-u>Denite grep -mode=normal<CR><CR>

**Comment by Shougo** [comment] 2017-04-19 23:58
I have tested it in async state source.
It is luggy.  So I think this is your machine lag.
Unfortutely, your machine is very slow.
I cannot reproduce it in non async state.

**Comment by Shougo** [comment] 2017-04-19 23:59
You can disable the highlight by `syntax off`.

**Comment by dmdque** [comment] 2017-04-20 00:00
![image](https://cloud.githubusercontent.com/assets/5205766/25207158/87544956-2521-11e7-8479-345852102f4a.png)

It's the same with `syntax off`

How can I set to non async so that it's faster?

**Comment by Shougo** [comment] 2017-04-20 00:01
I think MacOS X is slow.
Please test denite.nvim in Linux machine.

**Comment by dmdque** [comment] 2017-04-20 00:11
Ok I will do that tonight. But the thing is that the search results buffer with Unite.vim was perfectly fast even on MacOS.

**Comment by Shougo** [comment] 2017-04-20 01:27
I will check the performance bottleneck.

>  But the thing is that the search results buffer with Unite.vim was perfectly fast even on MacOS.

Because, it is different implementation.
Unite.vim just uses Vim scroll.
Denite.nvim implements the original scroll feature.

**Comment by Shougo** [comment] 2017-04-20 01:55
> call denite#custom#source('grep', 'max_candidates', 100)  " not sure if this is working

It works only asynchronous result.

**Comment by dmdque** [comment] 2017-04-20 02:08
Still slow without tmux.

I tried on Ubuntu 16.04 and it's also slow if #results > 1000. (It's an EC2 `t2.micro` instance, so it's only 1 CPU and 1GB RAM.)

I like the vim scroll version from Unite.vim. I like that it's simple and can be navigated with the same vim commands I use for everything.

I think I might just go back to using Unite unless the buffer can be implemented the same way for Denite.

**Comment by Shougo** [comment] 2017-04-20 02:17
I can optimize some redraw implementation.  So it will be better.
But I cannot reproduce the behavior without asynchronous state.

> I like the vim scroll version from Unite.vim. I like that it's simple and can be navigated with the same vim commands I use for everything.

It is simple, but it has many problems.
It is easy to conflicts with other configuration and plugins.
It is slow in huge candidates.

> I think I might just go back to using Unite unless the buffer can be implemented the same way for Denite.

Never come true.

**Comment by Shougo** [comment] 2017-04-20 02:24
@dmdque Please check the CPU usage in your machine.
rg process is exited properly? etc.

**Comment by dmdque** [comment] 2017-04-20 03:20
https://youtu.be/Qt4zbui6Vg8

I've also sent you an email with instructions on how to connect to my EC2 instance with slow Denite. You can ssh and see the slowness yourself.

**Comment by Shougo** [comment] 2017-04-20 03:29
https://www.youtube.com/watch?v=Qt4zbui6Vg8

Please see the CPU usage.
Very high.  So slow.

Two neovim instance exists.
One instance seems zombie.  You should check it.

**Comment by Shougo** [comment] 2017-04-20 03:35
I have reproduced CPU usage problem for my machine.
It should be fixed.

**Comment by Shougo** [comment] 2017-04-20 08:16
I have found the reason.  I will fix it.
Please wait.

**Comment by dmdque** [comment] 2017-04-20 08:17
Awesome, thank you!

**Comment by Shougo** [comment] 2017-04-23 09:41
Fixed.

**Closed** 2017-04-23 09:40 UTC
Labels: performance

**Comment by dmdque** [comment] 2017-04-23 19:41
Verified that it's fast now. Thanks Shougo!!

**Comment by Shougo** [comment] 2017-04-24 01:13
:-)
