### ISSUE TITLE
How to set the search box at the bottom

### ISSUE THREAD

**Issue by Menahem1227** [Shougo/denite.nvim#544] opened 2018-11-30 03:08 UTC
Hi @Shougo After using your deoplete plugin and other plugins, I am using your deinte plugin, now I have a problem How can i set the search box at the bottom
![1](https://user-images.githubusercontent.com/41671631/49266179-0a4bae00-f490-11e8-9264-05d32786cbf4.png)

**Comment by h-michael** [comment] 2018-12-02 09:43
@Marinus1227 
You should fill in [issue template](https://github.com/Shougo/denite.nvim/blob/master/.github/ISSUE_TEMPLATE.md) at first.

**Comment by Shougo** [comment] 2018-12-03 00:05
I don't reproduce the problem.
Please upload the minimal init.vim and the reproduce instructions.
If not, I will close the issue.

**Comment by Marinus1227** [comment] 2018-12-03 01:31
@Shougo  It's my fault. this is my mini ini.vim
```
"设置使用ag与grep
call denite#custom#var('grep', 'command', ['ag'])
nnoremap <Leader>pf :call denite#start([{'name': 'grep', 'args': ['', '', '!']}])<cr>
"当前目录搜索使用ag
call denite#custom#var('file_rec', 'command', ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
"其他grep设置
call denite#custom#var('grep', 'default_opts',['-i', '--vimgrep'])
call denite#custom#var('grep', 'recursive_opts', [])
call denite#custom#var('grep', 'pattern_opt', [])
call denite#custom#var('grep', 'separator', ['--'])
call denite#custom#var('grep', 'final_opts', [])

"ESC结束
call denite#custom#map('insert', '<esc>', '<denite:enter_mode:normal>', 'noremap')
call denite#custom#map('normal', '<esc>', '<denite:quit>', 'noremap')
"C-N,C-P上下移動
call denite#custom#map('insert', '<C-n>', '<denite:move_to_next_line>', 'noremap')
call denite#custom#map('insert', '<C-p>', '<denite:move_to_previous_line>', 'noremap')
"C-J,C-K分屏
call denite#custom#map('insert', '<C-j>', '<denite:do_action:split>', 'noremap')
call denite#custom#map('insert', '<C-k>', '<denite:do_action:vsplit>', 'noremap')

" 以下はdenite起動時に使用するキーマップ
"buffer列表
noremap <leader>db :Denite buffer<CR>
" 文件列表
noremap <leader>dbn :Denite -buffer-name=file file<CR>
" 最近使用文件列表
noremap <leader>dfo :Denite file_old -winheight=10 -vertical-preview -auto-preview<CR>
" 当前目录
noremap <leader>dfr :Denite file_rec -default-action=vsplit<CR>
"buffer列表
nnoremap <leader>dbb :<C-u>Denite buffer -buffer-name=file<CR>

"Denite line
nnoremap  <Leader>dl :<C-u>Denite line -auto-preview<CR>
nnoremap <silent> <expr><Space>l ":<C-u>DeniteWithCursorWord line<CR>"
" 指定显示字符
call denite#custom#option('default', 'prompt', '>')
" denite的起始位置
call denite#custom#option('default', 'direction', 'top')
```

**Comment by Marinus1227** [comment] 2018-12-03 01:33
> @ Marinus1227
> 你应该先填写[问题模板](https://github.com/Shougo/denite.nvim/blob/master/.github/ISSUE_TEMPLATE.md)。


Sorry, my English is not very good. I am a new github. The problem template is too complicated for me. I am sorry.

**Comment by Shougo** [comment] 2018-12-03 12:41
OK.  It is the reason.

```vim
call denite#custom#option('default', 'direction', 'top')
```

Please remove the line.

**Closed by Shougo** 2018-12-03 12:41 UTC
Labels: cannot reproduce, needs reproduction instructions
