### ISSUE TITLE
Auto-resize (sometimes) not working with large screen

### ISSUE THREAD

**Issue by petobens** [Shougo/denite.nvim#300] opened 2017-07-03 23:07 UTC
I'm using:
```vim
call denite#custom#option('default', {
            \ 'auto_resize': 1,
            \ 'statusline': 0,
            \ 'winheight': 15,
            \ 'updatetime': 100,
            \ 'reversed': 1,
            \ 'prompt': '❯',
            \ 'prompt_highlight': 'Function',
            \ 'highlight_matched_char': 'Function',
            \ 'highlight_matched_range': 'Normal',
            \ 'highlight_mode_insert': 'WildMenu'
            \ })
```
and getting the following beaviour when running `:Denite file_mru`:

![jul-03-2017 20-06-38](https://user-images.githubusercontent.com/2583971/27809982-30cdc3e2-602b-11e7-8ed2-f7998b9fb50c.gif)

**Comment by Shougo** [comment] 2017-07-04 03:51
Please read the issue template.
The reproduce ways and the minimal vimrc are required!
I cannot reproduce the problem.

**Comment by Shougo** [comment] 2017-07-04 03:51
I will close the issue.  If you cannot create them.

**Comment by Shougo** [comment] 2017-07-04 03:56
And please describe the issue.
I cannot understand it.
We have not ESP skills.

**Comment by Shougo** [comment] 2017-07-18 09:40
@petobens I will close it.  If no response.

**Comment by petobens** [comment] 2017-07-18 23:34
I''ll try to find a way to reproduce it and report back. Please don't close yet.

**Comment by Shougo** [comment] 2017-07-19 02:10
OK.  I will wait.

**Comment by petobens** [comment] 2017-07-22 15:24
The problem seems to be with `ag`. With the following minimal vimrc:
```vim
set nocompatible

let $DOTVIM = expand('$HOME/.vim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/denite.nvim
filetype plugin indent on

if executable('ag')
	call denite#custom#var('file_rec', 'command',
        \ ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
endif
```
If I run `Denite file_rec` then I can reproduce the behaviour as it can be seen in the following GIF:
![jul-22-2017 12-22-04](https://user-images.githubusercontent.com/2583971/28492365-68c62db4-6ed8-11e7-8881-5a9e0834e703.gif)

This also happens with the grep source when using `ag`. i.e:
```vim
if executable('ag')
	call denite#custom#var('grep', 'command', ['ag'])
	call denite#custom#var('grep', 'default_opts',
        \ ['--smart-case', '--vimgrep'])
	call denite#custom#var('grep', 'recursive_opts', [])
    call denite#custom#var('grep', 'pattern_opt', [])
	call denite#custom#var('grep', 'separator', ['--'])
	call denite#custom#var('grep', 'final_opts', [])
endif
```

**Comment by Shougo** [comment] 2017-07-23 13:48
OK.  I will test it.  But why "ag"?  I don't understand it.

**Comment by Shougo** [comment] 2017-07-23 13:49
@petobens You don't set `-auto-resize` in the minimal vimrc.
Please create the minimal vimrc properly.
I cannot test it.  Please re-create it.

**Comment by Shougo** [comment] 2017-07-23 13:52
I have the screenshot and it seems the feature.
Because the candidates are bigger than the window height.

**Comment by petobens** [comment] 2017-07-23 13:59
> @petobens You don't set -auto-resize in the minimal vimrc.
Silly me. You are right. Ok if I ever find a way to reproduce it i will report back. Thanks

**Comment by petobens** [comment] 2017-08-08 18:53
I was finally able to reproduce this behaviour consistently with the following minimal vimrc:
```vim
set nocompatible

let $DOTVIM = expand('$HOME/.vim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/denite.nvim
filetype plugin indent on
set hidden

call denite#custom#option('default', {
            \ 'auto_resize': 1,
            \ 'winheight': 15,
            \ 'reversed': 1,
            \ })
```
Now open nvim in a maximized terminal window and (as in the GIF) do the following:
i) run `:Denite file_rec`
ii) Press `<ESC>`
iii) run `:Denite file_rec` again
You will see in the last step that the denite window is not autoresized. If I remove the `set hidden` line this behaviour disappears.

![aug-08-2017 15-51-43](https://user-images.githubusercontent.com/2583971/29089099-93e1e606-7c51-11e7-8100-e2a0f67bee72.gif)

**Comment by Shougo** [comment] 2017-08-09 01:43
I will test it.

**Comment by Shougo** [comment] 2017-08-09 01:48
> You will see in the last step that the denite window is not autoresized. If I remove the set hidden line this behaviour disappears.

No.  Please see your screenshot.  The window is autoresized.
But the cursorposition is not the window bottom.

**Comment by petobens** [comment] 2017-08-09 01:51
@Shougo I don't understand. I expect the second window to open exactly like the first time (i.e without all those blank lines)

**Closed** 2017-08-09 23:35 UTC
Labels: cannot reproduce, cannot understand, reproduce ways

**Comment by petobens** [comment] 2017-08-10 03:34
Thank you
