### ISSUE TITLE
file_rec not working

### ISSUE THREAD

**Issue by rmolin88** [Shougo/denite.nvim#363] opened 2017-08-22 20:49 UTC
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary
- `Denite file_rec` doesnt find any files

## Environment Information (Required!)

 * denite version(SHA1): 
latest from vim-plug

 * OS:
Windows 7 64 - bit

 * Vim/neovim version:
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jul 19 2017 20:23:10)
MS-Windows 64-bit GUI version with OLE support
Included patches: 1-737
Compiled by hp@HP-PC
Huge version with GUI.  Features included (+) or not (-):
+acl                +clientserver       +cursorbind         +eval               +gettext/dyn        +libcall            +mouse              +path_extra         +reltime            +syntax             +textobjects        +viminfo            -xterm_save
+arabic             +clipboard          +cursorshape        +ex_extra           -hangul_input       +linebreak          +mouseshape         +perl/dyn           +rightleft          +tag_binary         +timers             +vreplace           
+autocmd            +cmdline_compl      +dialog_con_gui     +extra_search       +iconv/dyn          +lispindent         +multi_byte_ime/dyn +persistent_undo    +ruby/dyn           +tag_old_static     +title              +wildignore         
+balloon_eval       +cmdline_hist       +diff               +farsi              +insert_expand      +listcmds           +multi_lang         -postscript         +scrollbind         -tag_any_white      +toolbar            +wildmenu           
+browse             +cmdline_info       +digraphs           +file_in_path       +job                +localmap           +mzscheme/dyn       +printer            +signs              +tcl/dyn            +user_commands      +windows            
++builtin_terms     +comments           +directx            +find_in_path       +jumplist           +lua/dyn            +netbeans_intg      +profile            +smartindent        -termguicolors      +vertsplit          +writebackup        
+byte_offset        +conceal            -dnd                +float              +keymap             +menu               +num64              +python/dyn         +startuptime        -terminal           +virtualedit        -xfontset           
+channel            +cryptv             -ebcdic             +folding            +lambda             +mksession          +ole                +python3/dyn        +statusline         -tgetent            +visual             -xim                
+cindent            +cscope             +emacs_tags         -footer             +langmap            +modify_fname       +packages           +quickfix           -sun_workshop       -termresponse       +visualextra        +xpm_w32            
   system vimrc file: "$VIM\vimrc"
     user vimrc file: "$HOME\_vimrc"
 2nd user vimrc file: "$HOME\vimfiles\vimrc"
 3rd user vimrc file: "$VIM\_vimrc"
      user exrc file: "$HOME\_exrc"
  2nd user exrc file: "$VIM\_exrc"
  system gvimrc file: "$VIM\gvimrc"
    user gvimrc file: "$HOME\_gvimrc"
2nd user gvimrc file: "$HOME\vimfiles\gvimrc"
3rd user gvimrc file: "$VIM\_gvimrc"
       defaults file: "$VIMRUNTIME\defaults.vim"
    system menu file: "$VIMRUNTIME\menu.vim"
Compilation: cl -c /W3 /nologo  -I. -Iproto -DHAVE_PATHDEF -DWIN32  -DFEAT_CSCOPE  -DFEAT_NETBEANS_INTG -DFEAT_JOB_CHANNEL   -DFEAT_XPM_W32   -DWINVER=0x0501 -D_WIN32_WINNT=0x0501  /Fo.\ObjGXOULYHTRZAMD64/ /MP -DHAVE_STDINT_H /Ox /GL -DNDEBUG  /MD -DFEAT_OLE -DFEAT_MBYTE_IME -DDYNAMIC_IME -DGLOBAL_IME -DFEAT_MBYTE -DFEAT_GUI_W32 -DFEAT_DIRECTX -DDYNAMIC_DIRECTX -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_TCL -DDYNAMIC_TCL -DDYNAMIC_TCL_DLL=\"tcl86.dll\" -DDYNAMIC_TCL_VER=\"8.6\" -DFEAT_LUA -DDYNAMIC_LUA -DDYNAMIC_LUA_DLL=\"lua53.dll\" -DFEAT_PYTHON -DDYNAMIC_PYTHON -DDYNAMIC_PYTHON_DLL=\"python27.dll\" -DFEAT_PYTHON3 -DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL=\"python36.dll\" -DFEAT_MZSCHEME -I "C:\Users\hp\Desktop\racket-x64\include" -DDYNAMIC_MZSCHEME -DDYNAMIC_MZSCH_DLL=\"libracketxxxxxxx.dll\" -DDYNAMIC_MZGC_DLL=\"libmzgcxxxxxxx.dll\" -DFEAT_PERL -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DDYNAMIC_PERL -DDYNAMIC_PERL_DLL=\"perl526.dll\" -DFEAT_RUBY -DDYNAMIC_RUBY -DDYNAMIC_RUBY_VER=24 -DDYNAMIC_RUBY_DLL=\"x64-msvcrt-ruby240.dll\" -DFEAT_HUGE /Fd.\ObjGXOULYHTRZAMD64/ /Zi
Linking: link /RELEASE /nologo /subsystem:windows /LTCG:STATUS oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib uuid.lib /machine:AMD64 gdi32.lib version.lib   winspool.lib comctl32.lib advapi32.lib shell32.lib  /machine:AMD64  msvcrt.lib oleaut32.lib user32.lib  /nodefaultlib:lua53.lib  /STACK:8388608  /nodefaultlib:python27.lib /nodefaultlib:python36.lib   "C:\TCL\lib\tclstub86.lib" WSock32.lib .\xpm\x64\lib-vc14\libXpm.lib /PDB:gvim.pdb -debug
```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
function! s:set_stdpaths() abort
	if has('win32')
		let g:std_config_path = (exists('$APPDATA')) ? $APPDATA : "~\\AppData\\Roaming"
		let g:std_data_path = (exists('$LOCALAPPDATA')) ? $LOCALAPPDATA : "~\\AppData\\Local"
		let g:std_cache_path = (exists('$TEMP')) ? $TEMP : "~\\AppData\\Local\\Temp"
	else
		let g:std_config_path = (exists('$XDG_CONFIG_HOME')) ? $XDG_CONFIG_HOME : "~/.config"
		let g:std_data_path = (exists('$XDG_DATA_HOME')) ? $XDG_DATA_HOME : "~/.local/share"
		let g:std_cache_path = (exists('$XDG_CACHE_HOME')) ? $XDG_CACHE_HOME : "~/.cache"
	endif
endfunction

call s:set_stdpaths()

let vim_plugins =  g:std_data_path . '/vim_plugins'
execute "source " . vim_plugins . '/plug/plug.vim'
call plug#begin(vim_plugins)
Plug 'Shougo/denite.nvim', { 'as' : has('nvim') ? 'nvim_denite' : 'vim_denite' }
call plug#end()

" vim:tw=78:ts=2:sts=2:sw=2:
```

## Screen shot (if possible)
![denite_bug](https://user-images.githubusercontent.com/5428479/29586670-8997ed22-8759-11e7-81a9-8bf99ac11b42.png)

## Upload the log file
[vim_log.txt](https://github.com/Shougo/denite.nvim/files/1243305/vim_log.txt)

**Comment by Shougo** [comment] 2017-08-23 02:04
I don't test denite.nvim in Windows.
So I don't know why...

@skeept Ping.

**Comment by Shougo** [comment] 2017-08-23 02:04
https://github.com/Shougo/denite.nvim/pull/187

**Comment by rmolin88** [comment] 2017-08-23 11:22
It must have being a recent commit because it was working last week. This
issue is new. It's only files rec. Files and all the others seen to work.
BTW I provided a 10mb vim log

**Comment by Shougo** [comment] 2017-08-24 01:55
Please use `git bisect`.

**Comment by Shougo** [comment] 2017-08-24 02:00
And you can check the command line by `<denite:print_messages>` mapping.
It is mapped to normal mode M.

**Comment by Rantanen** [comment] 2017-09-01 12:09
I encountered the opposite issue in Windows where Denite ended up finding the same files multiple times. The performance was atrocious as Denite kept crawling through the directory structure multiple times, resulting in hundreds of thousands of files.

This happened only in one (somewhat large) directory structure. Could be some weird symlinking or similar going on.

In the end I worked around my issue by changing file_rec command to 'ag', which I prefer anyway so didn't look any more into the problem. Just leaving this comment here in case these problems share a root cause (despite the completely different results) and this will help in narrowing it down.

**Comment by Shougo** [comment] 2017-09-02 07:56
I have not much test time in Windows.
I don't know why.

**Comment by skeept** [comment] 2017-09-16 05:39
I think with recent merge file_rec in windows works better. Do you still have the same issue?

**Comment by Shougo** [comment] 2017-09-16 06:36
OK.  Please read the reviews.

**Comment by Shougo** [comment] 2017-09-16 06:37
@Rantanen @rmolin88 Please test the PR.

**Comment by Shougo** [comment] 2017-09-18 01:46
#369 is merged.

Hm....
No comment.
I will close it.

**Closed by Shougo** 2017-09-18 01:46 UTC
Labels: help wanted, Windows

**Comment by rmolin88** [comment] 2017-09-18 19:36
I was just able to test it. It looks good. Thanks for the support and a great plugin!

**Comment by Shougo** [comment] 2017-09-19 01:25
OK
