### ISSUE TITLE
:Denite buffer intermittently does not close

### ISSUE THREAD

**Issue by renyard** [Shougo/denite.nvim#649] opened 2019-06-06 12:23 UTC
# Problems summary
`:Denite buffer` intermittently will not close when selecting and pressing enter on a buffer to switch to. The cursor remains in the status bar and cannot be navigated out.

## Expected
When selecting a buffer and pressing enter, that buffer should open and be focused and the Denite window should close.

## Environment Information (Required!)

 * denite version (SHA1): 6937f1d

 * OS: macOS 10.14.4

 * Vim/neovim version: Vim 8.1.950

 * `:checkhealth` or `:CheckHealth` result(neovim only): n/a

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
map <C-t> :Denite buffer<Return>
map <C-p> :Denite file/rec<Return>

call denite#custom#filter('matcher_ignore_globs', 'ignore_globs',
    \ [ '.git/', 'node_modules/', 'reports/', 'coverage/', 'logs/',
    \ 'images/', '*.min.*', 'img/', 'fonts/'])

call denite#custom#var('file/rec', 'command',
    \ ['find', '-L', ':directory',
    \ '-path', '*/.*/*', '-prune', '-o',
    \ '-path', '*/node_modules/*', '-prune', '-o',
    \ '-path', '*/coverage/*', '-prune', '-o',
    \ '-type', 'l', '-print', '-o', '-type', 'f', '-print']
    \ )
call denite#custom#option('file/rec', {'start_filter': v:true})

autocmd FileType denite call s:denite_my_settings()
function! s:denite_my_settings() abort
  nnoremap <silent><buffer><expr> <CR>
  \ denite#do_map('do_action')
  nnoremap <silent><buffer><expr> d
  \ denite#do_map('do_action', 'delete')
  nnoremap <silent><buffer><expr> p
  \ denite#do_map('do_action', 'preview')
  nnoremap <silent><buffer><expr> q
  \ denite#do_map('quit')
  nnoremap <silent><buffer><expr> i
  \ denite#do_map('open_filter_buffer')
  nnoremap <silent><buffer><expr> <Space>
  \ denite#do_map('toggle_select').'j'
endfunction
```

## How to reproduce problems from neovim startup (Required!)

 1. Open two or more buffers.
2. Open Denite via `:Denite buffer` or <c-t> mapping.
3. Press enter to select the first buffer in the list.
4. Buffer does not open, Denite window remains open. Cursor is in the status bar and cannot navigate back to the buffer or Denite window.

## Screenshot (if possible)
![image](https://user-images.githubusercontent.com/103872/59032068-49065a80-885d-11e9-83d8-782e8899b338.png)

## Upload the log file
https://gist.github.com/renyard/74cc4e7143c441c5107e42d0a28d849e

**Comment by kuator** [comment] 2019-06-06 12:32
![image](https://user-images.githubusercontent.com/25168308/59033017-78cb5780-8889-11e9-84d1-caf1b09710ee.png)

**Comment by kuator** [comment] 2019-06-06 12:34
I also cannot type text, here is the screenshot
![Screenshot from 2019-06-06 18-30-45](https://user-images.githubusercontent.com/25168308/59033080-a57f6f00-8889-11e9-9745-8f0416d3862f.png)

**Comment by Shougo** [comment] 2019-06-06 13:47
> After updating denite, I cannot type text either, here is the screenshot

https://github.com/Shougo/denite.nvim#examples

**Comment by Shougo** [comment] 2019-06-06 13:49
I have tested the following vimrc.

```vim
set runtimepath+=~/work/denite.nvim/

filetype plugin indent on
syntax enable

colorscheme desert

filetype plugin indent on

" call denite#custom#option('default', {'start_filter' : 1})

autocmd FileType denite call s:denite_my_settings()
function! s:denite_my_settings() abort
  nnoremap <silent><buffer><expr> <CR>
  \ denite#do_map('do_action')
  nnoremap <silent><buffer><expr> d
  \ denite#do_map('do_action', 'delete')
  nnoremap <silent><buffer><expr> p
  \ denite#do_map('do_action', 'preview')
  nnoremap <silent><buffer><expr> q
  \ denite#do_map('quit')
  nnoremap <silent><buffer><expr> i
  \ denite#do_map('open_filter_buffer')
  nnoremap <silent><buffer><expr> <Space>
  \ denite#do_map('toggle_select').'j'
endfunction
```

It works.  Closing.  Because you have not the minimal vimrc and I have not reproduce it in the minimal vimrc.

> **Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

Please read the issue template.

**Closed by Shougo** 2019-06-06 13:49 UTC

**Comment by kuator** [comment] 2019-06-06 13:56
@Shougo, so, okay, the settings have changed, I guess? Then, I just roll back, cause I'm lazy to change settings.

**Comment by Shougo** [comment] 2019-06-08 09:06
>  so, okay, the settings have changed, I guess? Then, I just roll back, cause I'm too lazy to change the vimrc.

Yes.  Denite.nvim is already major updated.
You need to migrate.

**Comment by kuator** [comment] 2019-06-08 12:35
@Shougo, okay, if you say so, dark master
