### ISSUE TITLE
Flickering prompt

### ISSUE THREAD

**Issue by AlexMasterov** [Shougo/denite.nvim#249] opened 2017-04-14 07:45 UTC
## Environment Information

 * denite version(SHA1): #e451f45
 * OS: Windows 10 (15063)
 * Vim/neovim version: GVim 8.0 (563p)

## Screen shot
![Imgur](http://i.imgur.com/74SMmDw.gif)

**Comment by Shougo** [comment] 2017-04-14 09:19
It is Vim problem...

**Comment by Shougo** [comment] 2017-04-14 09:23
It is reproduced on GVim in Linux.
It is not reproduced on terminal Vim.

**Comment by AlexMasterov** [comment] 2017-04-14 15:19
Thanks for the reply.
But what is the problem here? [redraw](https://github.com/Shougo/denite.nvim/blob/737f7b171966b809e4a8da2dcb2b17c83985ea1e/rplugin/python3/denite/prompt/prompt.py#L149)?

I'm going to create an issue.

**Comment by Shougo** [comment] 2017-04-17 10:44
> It is reproduced on GVim in Linux.

This behavior is async only in Linux.  I will research it more.

**Comment by Shougo** [comment] 2017-04-18 01:24
I will fix the problem.  Please wait.

**Comment by Shougo** [comment] 2017-04-18 01:27
You can close https://github.com/vim/vim/issues/1637 issue.

**Comment by Shougo** [comment] 2017-04-18 01:46
I have found some bug in GVim.
In `<silent>` mapping, the cursor is not hidden.

```vim
function! Test() abort
  while 1
    redraw
    echo getchar(0)
    sleep 10m
  endwhile
endfunction

nnoremap <silent> ss  :<C-u>call Test()<CR>
nnoremap sg  :<C-u>call Test()<CR>
```

If you press `ss`, the cursor not hidden.
But you press `sg`, the cursor is hidden.

**Comment by AlexMasterov** [comment] 2017-04-18 08:18
Thank you for taking care!

It is reproduced on Windows 10 in GVim too.

**Comment by Shougo** [comment] 2017-04-19 22:42
Fixed.

Note: This works for GVim only.

**Comment by AlexMasterov** [comment] 2017-04-19 23:29
Thank you. It looks like a hack :)
But now flickers the place where the cursor is hidden and the text in the prompt continues to flicker.

Don't waste time on it, I migrate to NVim.

**Comment by Shougo** [comment] 2017-04-19 23:33
> But now flickers the place where the cursor is hidden and the text in the prompt continues to flicker.

Because, I cannot reproduce the prompt flicker.
I have reproduced the buffer flicker though.
It is better in Linux GVim.

**Comment by AlexMasterov** [comment] 2017-04-19 23:37
Why don't you create an issue for this bug?

**Comment by Shougo** [comment] 2017-04-19 23:41
> Why don't you create an issue for this bug?

You have created it.

**Comment by Shougo** [comment] 2017-04-19 23:43
The problem is reproduced in `<silent>` mapping only in GVim Linux.

I think problem https://github.com/Shougo/denite.nvim/issues/249#issuecomment-294648432 is related.
But this is different behavior in Windows.

**Comment by AlexMasterov** [comment] 2017-04-20 01:01
`guicursor` is not restored after closing the denite :(

**Comment by Shougo** [comment] 2017-04-20 01:25
Really?  I cannot reproduce it.
Please create new issue with the reproduce ways.

**Comment by chrisbra** [comment] 2017-04-20 14:33
Shougo wrote: 

> In <silent> mapping, the cursor is not hidden.

The documentation does not talk about hiding the cursor with `<silent>` mappings, so this is no bug here.

**Comment by chrisbra** [comment] 2017-04-20 14:35
Shougo wrote:

> You can close vim/vim#1637 issue.

BTW: I would appreciate leaving a comment at the original issue, if it can be closed, instead of leaving it open.

**Comment by Shougo** [comment] 2017-04-21 02:04
> BTW: I would appreciate leaving a comment at the original issue, if it can be closed, instead of leaving it open.

I had thought it is fixed by guicursor hack.
But it is not fixed in GVim Windows...

**Comment by Shougo** [comment] 2017-04-21 02:18
@AlexMasterov You should create the minimal vimrc to reproduce the problem.
I think the problem is when use `<silent>` mappings only.

**Comment by Shougo** [comment] 2017-04-21 02:37
It may be from `redrawstatus`.
It flicks Vim and neovim.
I will fix the problem.  Please wait.

**Comment by Shougo** [comment] 2017-04-21 02:38
I think it is related to https://github.com/Shougo/denite.nvim/issues/254.

**Comment by Shougo** [comment] 2017-04-21 02:46
@AlexMasterov 

> guicursor is not restored after closing the denite :(

Please create the new issue.

**Comment by Shougo** [comment] 2017-04-23 09:41
Fixed.

**Closed** 2017-04-23 09:40 UTC

**Comment by Shougo** [comment] 2017-04-24 10:28
> guicursor is not restored after closing the denite :(

https://github.com/Shougo/denite.nvim/issues/260

Another person created the issue.

**Comment by AlexMasterov** [comment] 2017-04-25 08:50
@Shougo finally, thank you :+1:
