### ISSUE TITLE
Incorrect assumptions made regarding colorschemes

### ISSUE THREAD

**Issue by frioux** [Shougo/denite.nvim#288] opened 2017-05-30 00:34 UTC
# Problems summary

Some colorschemes (!!!) make it impossible to select items.

## Expected

Press enter on an item and open the file (or whatever.)

## Environment Information (Required!)

 * denite version(SHA1): e8a0b3f

 * OS: Ubuntu 17.04

 * Vim/neovim version: 8.0.95

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/denite.nvim/
colorscheme elflord " or inkpot or almost any other colorscheme
```

## The reproduce ways from neovim starting (Required!)

 1. Start vim **from a terminal**
 2. `:Denite file` (or any other source)
 3. `<Enter>`

## Screen shot (if possible)

![zfp--bin-zsh-104](https://cloud.githubusercontent.com/assets/8163/26564389/f6db6dbc-4494-11e7-9df4-5b0f21507807.png)

## Upload the log file

```
[denite] Traceback (most recent call last):
[denite]   File "/home/frew/code/dotfiles/vim/bundle/denite/rplugin/python3/denite/ui/default.py", line 63, in start
[denite]     self._start(sources, context)
[denite]   File "/home/frew/code/dotfiles/vim/bundle/denite/rplugin/python3/denite/ui/default.py", line 128, in _start
[denite]     status = self._prompt.start()
[denite]   File "/home/frew/code/dotfiles/vim/bundle/denite/rplugin/python3/denite/prompt/prompt.py", line 189, in start
[denite]     raise e
[denite]   File "/home/frew/code/dotfiles/vim/bundle/denite/rplugin/python3/denite/prompt/prompt.py", line 179, in start
[denite]     callback=self.on_harvest,
[denite]   File "/home/frew/code/dotfiles/vim/bundle/denite/rplugin/python3/denite/ui/prompt.py", line 92, in on_keypress
[denite]     return self.action.call(self, m.group('action'))
[denite]   File "/home/frew/code/dotfiles/vim/bundle/denite/rplugin/python3/denite/prompt/action.py", line 139, in call
[denite]     return fn(prompt, params)
[denite]   File "/home/frew/code/dotfiles/vim/bundle/denite/rplugin/python3/denite/ui/action.py", line 15, in _do_action
[denite]     return prompt.denite.do_action(params)
[denite]   File "/home/frew/code/dotfiles/vim/bundle/denite/rplugin/python3/denite/ui/default.py", line 550, in do_action
[denite]     self.quit()
[denite]   File "/home/frew/code/dotfiles/vim/bundle/denite/rplugin/python3/denite/ui/default.py", line 517, in quit
[denite]     self.quit_buffer()
[denite]   File "/home/frew/code/dotfiles/vim/bundle/denite/rplugin/python3/denite/ui/default.py", line 479, in quit_buffer
[denite]     self.cleanup()
[denite]   File "/home/frew/code/dotfiles/vim/bundle/denite/rplugin/python3/denite/ui/default.py", line 474, in cleanup
[denite]     self._vim.command('silent doautocmd ColorScheme')
[denite] vim.error: Vim(highlight):E417: missing argument: ctermbg=
[denite] 
[denite] During handling of the above exception, another exception occurred:
[denite] 
[denite] Traceback (most recent call last):
[denite]   File "<string>", line 14, in _temporary_scope
[denite]   File "/home/frew/code/dotfiles/vim/bundle/denite/rplugin/python3/denite/ui/default.py", line 65, in start
[denite]     self.cleanup()
[denite]   File "/home/frew/code/dotfiles/vim/bundle/denite/rplugin/python3/denite/ui/default.py", line 474, in cleanup
[denite]     self._vim.command('silent doautocmd ColorScheme')
[denite] vim.error: Vim(highlight):E417: missing argument: ctermbg=
[denite] Please execute :messages command.
```

**Comment by Shougo** [comment] 2017-05-30 01:42
I have tested it in the minimal vimrc, but I cannot reproduce the error.

I think you or other plugins defined the incorrect ColorScheme autocmd.
Have you tested the minimal vimrc?

**Comment by Shougo** [comment] 2017-05-30 01:44
```vim
" Your minimal init.vim
set runtimepath+=~/path/to/denite.nvim/
colorscheme elflord " or inkpot or almost any other colorscheme
```

It does not have PowerLine plugin, but your screen shot has PowerLine plugin why?

Please upload the real minimal vimrc!
I will close the issue.

**Closed by Shougo** 2017-05-30 01:44 UTC
Labels: cannot reproduce, reproduce ways

**Comment by frioux** [comment] 2017-05-30 03:24
You're absolutely right; I thought I was sourcing the minimal vimrc and wasn't.  If you care to look into it, the plugin that clashes with Denite is [quick-scope](https://github.com/unblevable/quick-scope).  It looks like there are already patches to fix the issue.  Thanks for your patience.

**Comment by Shougo** [comment] 2017-05-30 03:46
OK.
